name: mtplus

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.7
  - jupyterlab
  - pandas
  - numpy
  - numba
  - netCDF4
  - mpi4py
  - scipy
  - matplotlib
  - cartopy
  - graph-tool
